In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
iris = pd.read_csv("iris.csv")
iris.shape
iris.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [4]:
# input
x = iris.iloc[:, [0, 3]].values
  
# output
y = iris.iloc[:, 4].values
print(x)
print(y)

[[5.1 0.2]
 [4.9 0.2]
 [4.7 0.2]
 [4.6 0.2]
 [5.  0.2]
 [5.4 0.4]
 [4.6 0.3]
 [5.  0.2]
 [4.4 0.2]
 [4.9 0.1]
 [5.4 0.2]
 [4.8 0.2]
 [4.8 0.1]
 [4.3 0.1]
 [5.8 0.2]
 [5.7 0.4]
 [5.4 0.4]
 [5.1 0.3]
 [5.7 0.3]
 [5.1 0.3]
 [5.4 0.2]
 [5.1 0.4]
 [4.6 0.2]
 [5.1 0.5]
 [4.8 0.2]
 [5.  0.2]
 [5.  0.4]
 [5.2 0.2]
 [5.2 0.2]
 [4.7 0.2]
 [4.8 0.2]
 [5.4 0.4]
 [5.2 0.1]
 [5.5 0.2]
 [4.9 0.2]
 [5.  0.2]
 [5.5 0.2]
 [4.9 0.1]
 [4.4 0.2]
 [5.1 0.2]
 [5.  0.3]
 [4.5 0.3]
 [4.4 0.2]
 [5.  0.6]
 [5.1 0.4]
 [4.8 0.3]
 [5.1 0.2]
 [4.6 0.2]
 [5.3 0.2]
 [5.  0.2]
 [7.  1.4]
 [6.4 1.5]
 [6.9 1.5]
 [5.5 1.3]
 [6.5 1.5]
 [5.7 1.3]
 [6.3 1.6]
 [4.9 1. ]
 [6.6 1.3]
 [5.2 1.4]
 [5.  1. ]
 [5.9 1.5]
 [6.  1. ]
 [6.1 1.4]
 [5.6 1.3]
 [6.7 1.4]
 [5.6 1.5]
 [5.8 1. ]
 [6.2 1.5]
 [5.6 1.1]
 [5.9 1.8]
 [6.1 1.3]
 [6.3 1.5]
 [6.1 1.2]
 [6.4 1.3]
 [6.6 1.4]
 [6.8 1.4]
 [6.7 1.7]
 [6.  1.5]
 [5.7 1. ]
 [5.5 1.1]
 [5.5 1. ]
 [5.8 1.2]
 [6.  1.6]
 [5.4 1.5]
 [6.  1.6]
 [6.7 1.5]
 [6.3 1.3]
 [5.6 1.3]
 [5.5 1.3]
 [5.5 1.2]

In [4]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.60, random_state = 0)

In [5]:
print(ytest)

['Virginica' 'Versicolor' 'Setosa' 'Virginica' 'Setosa' 'Virginica'
 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor' 'Virginica' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Setosa' 'Versicolor' 'Versicolor'
 'Setosa' 'Setosa' 'Virginica' 'Versicolor' 'Setosa' 'Setosa' 'Virginica'
 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Setosa' 'Virginica'
 'Versicolor' 'Setosa' 'Virginica' 'Virginica' 'Versicolor' 'Setosa'
 'Versicolor' 'Versicolor' 'Versicolor' 'Virginica' 'Setosa' 'Virginica'
 'Setosa' 'Setosa' 'Versicolor' 'Virginica' 'Virginica' 'Virginica'
 'Virginica' 'Versicolor' 'Virginica' 'Versicolor' 'Versicolor'
 'Virginica' 'Virginica' 'Virginica' 'Virginica' 'Versicolor' 'Virginica'
 'Versicolor' 'Setosa' 'Virginica' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Virginica' 'Setosa' 'Setosa' 'Virginica' 'Versicolor'
 'Setosa' 'Setosa' 'Versicolor' 'Setosa' 'Virginica' 'Versicolor' 'Setosa'
 'Versicolor' 'Virginica' 'Versicolor' 'Setosa' 'Virginica' 'Virginica'
 'Vir

In [6]:
#from sklearn.ensemble import RandomForestClassifier
#classifier = RandomForestClassifier(random_state = 0)
#classifier.fit(xtrain, ytrain)

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(xtrain, ytrain)

GaussianNB()

In [7]:
y_pred = classifier.predict(xtest)

In [8]:
ytest
print(y_pred)
print(ytest)

['Virginica' 'Versicolor' 'Setosa' 'Virginica' 'Setosa' 'Virginica'
 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Setosa' 'Versicolor' 'Versicolor'
 'Setosa' 'Setosa' 'Virginica' 'Versicolor' 'Setosa' 'Setosa' 'Virginica'
 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Setosa' 'Virginica'
 'Versicolor' 'Setosa' 'Virginica' 'Virginica' 'Versicolor' 'Setosa'
 'Versicolor' 'Versicolor' 'Versicolor' 'Virginica' 'Setosa' 'Virginica'
 'Setosa' 'Setosa' 'Versicolor' 'Virginica' 'Virginica' 'Versicolor'
 'Virginica' 'Versicolor' 'Virginica' 'Versicolor' 'Versicolor'
 'Virginica' 'Versicolor' 'Versicolor' 'Virginica' 'Versicolor'
 'Virginica' 'Versicolor' 'Setosa' 'Virginica' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Virginica' 'Setosa' 'Setosa' 'Virginica'
 'Versicolor' 'Setosa' 'Setosa' 'Versicolor' 'Setosa' 'Virginica'
 'Versicolor' 'Setosa' 'Versicolor' 'Virginica' 'Versicolor' 'Setosa'
 'Virginica' 'Virginica' 

In [9]:
from sklearn.metrics import confusion_matrix
from sklearn import metrics
cm = confusion_matrix(ytest, y_pred)
print(metrics.classification_report(ytest, y_pred))
  
print ("Confusion Matrix : \n", cm)

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        26
  Versicolor       0.89      1.00      0.94        33
   Virginica       1.00      0.87      0.93        31

    accuracy                           0.96        90
   macro avg       0.96      0.96      0.96        90
weighted avg       0.96      0.96      0.96        90

Confusion Matrix : 
 [[26  0  0]
 [ 0 33  0]
 [ 0  4 27]]


In [10]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(ytest, y_pred))

Accuracy :  0.9555555555555556
