In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
dataset = pd.read_csv("breast_cancer.csv")
dataset.shape

(683, 11)

In [3]:
dataset.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [13]:
# input
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 10].values


In [15]:
print(x)
print(y)

[[1000025       5       1 ...       3       1       1]
 [1002945       5       4 ...       3       2       1]
 [1015425       3       1 ...       3       1       1]
 ...
 [ 888820       5      10 ...       8      10       2]
 [ 897471       4       8 ...      10       6       1]
 [ 897471       4       8 ...      10       4       1]]
[2 2 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 2 4 4 2 2 4 2 2 2 2 2 2 4 2 2 2 4 2
 4 4 4 4 4 4 2 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 2 4 2 4 4 2 2 4 2 4 4 2
 2 2 2 2 2 2 2 2 4 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 2 4 4 4 4 4 2 4 2 4 4
 4 2 2 2 4 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 4 2 2 4 2 4
 4 2 2 4 2 2 4 4 2 2 2 2 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 4 2 4 4 4 2 4
 4 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 4 4 2 4 4 4 2 2 4 2 2 4 4 4 4 2 4 4
 2 4 4 4 2 4 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 4 2 4 4 4 2 2 2 2 4 4 4 4 4 2 4
 4 4 2 4 2 4 4 2 2 2 2 4 2 2 4 4 4 4 4 2 4 4 2 2 4 4 2 2 4 4 2 4 2 4 4 2 2
 4 2 2 2 4 2 2 4 4 2 2 4 2 4 2 2 4 2 4 4 4 2 2 4 4 2 4 2 2 4 4 2

In [16]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.80, random_state = 0)

In [17]:
print(ytest)

[2 2 4 4 2 2 2 4 2 2 4 2 4 2 2 2 4 4 4 2 2 2 4 2 4 4 2 2 2 4 2 4 4 2 2 2 4
 4 2 4 2 2 2 2 2 2 2 4 2 2 4 2 4 2 2 2 4 2 2 4 2 2 2 2 2 2 2 2 4 4 2 2 2 2
 2 2 4 2 2 2 4 2 4 2 2 4 2 2 4 2 4 2 4 4 4 2 4 4 4 2 2 2 4 4 2 2 4 4 2 2 4
 2 2 4 2 2 2 4 2 2 2 4 2 2 4 4 2 4 2 4 2 2 4 2 2 4 2 4 2 2 2 4 2 2 2 2 4 2
 4 2 4 4 2 2 2 2 4 4 2 4 4 4 4 4 4 2 2 2 2 2 2 4 4 4 2 2 2 4 2 2 4 4 2 4 2
 2 4 4 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 2 4 4 2 4 2 2 2 4 2 2 2 2 4 4 2 2 4 4
 2 2 4 4 2 4 2 4 4 2 2 2 4 2 4 2 4 2 2 2 2 2 4 2 2 4 2 2 4 2 2 2 2 2 4 2 2
 4 2 4 2 2 4 4 4 2 2 2 2 2 2 4 4 2 2 2 2 2 2 2 4 2 2 4 2 2 2 2 2 2 2 4 2 2
 2 4 4 2 4 2 2 2 4 2 2 2 4 4 2 4 2 2 4 2 2 2 2 2 2 2 4 4 4 4 2 4 2 4 2 4 4
 4 2 2 4 2 2 2 2 4 4 2 2 2 4 2 2 4 2 2 2 2 4 4 2 2 2 2 2 2 2 2 2 2 2 4 2 4
 2 2 2 2 2 2 4 4 4 4 2 2 4 2 4 2 4 2 2 2 2 4 2 4 2 2 2 2 4 2 2 4 2 2 2 2 2
 2 2 4 2 4 2 2 2 4 2 2 2 2 2 4 2 2 2 2 4 2 2 4 2 2 2 2 4 4 2 2 2 2 4 2 2 4
 2 2 2 2 4 4 2 4 2 4 2 2 2 4 4 4 2 2 2 2 2 2 2 2 4 4 2 2 2 2 2 2 2 4 4 2 2
 2 2 4 4 4 2 4 2 4 2 2 2 

In [18]:
#from sklearn.ensemble import RandomForestClassifier
#classifier = RandomForestClassifier(random_state = 0)
#classifier.fit(xtrain, ytrain)

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(xtrain, ytrain)

GaussianNB()

In [19]:
y_pred = classifier.predict(xtest)

In [20]:
ytest
print(y_pred)
print(ytest)

[2 2 4 2 2 2 2 4 2 4 4 2 4 2 2 2 4 4 4 2 2 2 2 2 4 4 2 2 2 2 2 4 4 2 2 2 4
 2 2 4 2 4 2 2 2 2 4 4 2 2 4 2 2 2 2 2 4 2 2 2 2 2 2 2 2 2 2 2 2 2 2 4 2 2
 2 2 2 2 2 2 4 2 4 2 2 4 2 4 4 2 2 2 4 2 2 2 2 4 2 2 2 2 4 2 2 2 4 2 2 2 2
 2 2 4 2 2 2 2 2 2 2 4 2 2 4 4 2 4 2 4 2 2 4 2 2 4 2 2 2 2 2 2 2 2 2 4 4 2
 4 2 4 2 2 2 2 2 4 4 2 4 4 4 4 2 2 2 2 2 2 2 2 4 4 4 2 2 2 2 2 2 2 2 2 4 2
 2 4 4 2 2 2 2 2 2 2 4 2 4 4 2 2 2 2 2 4 2 2 4 2 2 2 4 2 2 2 2 4 4 2 2 4 4
 2 2 2 2 2 4 2 4 4 2 2 2 2 2 4 2 4 2 2 2 2 2 4 2 2 4 2 2 4 2 2 2 2 2 2 2 2
 4 2 4 2 2 4 4 4 2 2 2 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 4 2 2 2 2 2 2 2 4 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 4 2 4 2 2 4 2 2 2 2 2 2 2 2 4 2 4 2 4 2 4 2 4 4
 2 2 2 4 2 2 2 2 2 4 2 2 2 4 2 2 4 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 4
 2 2 2 2 2 2 4 4 4 4 2 2 4 2 4 2 4 2 2 2 2 4 2 4 2 2 2 2 2 2 2 4 2 2 2 2 2
 2 2 2 2 4 2 4 2 2 2 2 2 2 2 4 2 2 2 2 4 2 2 2 4 2 2 2 4 4 2 2 2 2 4 2 2 4
 2 2 2 4 4 4 2 4 2 2 2 2 2 2 2 4 2 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2 2 4 2 2 2
 2 2 4 2 4 2 2 2 4 2 2 2 

In [21]:
from sklearn.metrics import confusion_matrix
from sklearn import metrics
cm = confusion_matrix(ytest, y_pred)
print(metrics.classification_report(ytest, y_pred))
  
print ("Confusion Matrix : \n", cm)

              precision    recall  f1-score   support

           2       0.84      0.97      0.90       357
           4       0.92      0.66      0.77       190

    accuracy                           0.86       547
   macro avg       0.88      0.81      0.83       547
weighted avg       0.87      0.86      0.85       547

Confusion Matrix : 
 [[346  11]
 [ 65 125]]


In [22]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(ytest, y_pred))

Accuracy :  0.8610603290676416
