In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Dataset:
It is having investment and profit of 50 Starts up at USA.

In [2]:
Score = pd.read_csv("startup.csv")
Score.shape
Score.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [3]:
#preparing the data
X = Score.drop('Profit', axis=1)
y = Score['Profit']

In [4]:
print(X)
print(y)

    R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1   162597.70       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41       118671.85        383199.62
4   142107.34        91391.77        366168.42
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [6]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [7]:
#printing parameters:
print(reg.intercept_)
print(reg.coef_)

42989.00816508666
[0.77884104 0.0293919  0.03471025]


In [8]:
#making predictions:
y_pred = reg.predict(X_test)

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


% Administration column is divided by 2

In [22]:
Score = pd.read_csv("startup.csv")
Score.shape
Score.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [23]:
Score['Administration'] = Score['Administration']/2

In [24]:
Score.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       68448.900        471784.10  192261.83
1  162597.70       75688.795        443898.53  191792.06
2  153441.51       50572.775        407934.54  191050.39
3  144372.41       59335.925        383199.62  182901.99
4  142107.34       45695.885        366168.42  166187.94

In [25]:
#preparing the data
X1 =Score.drop('Profit', axis=1)
y1= Score['Profit']

In [26]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=0)

In [27]:
regressor1 = LinearRegression()
regressor1.fit(X1_train, y1_train)

LinearRegression()

In [28]:
y1_pred = regressor1.predict(X1_test)

In [29]:
df1 = pd.DataFrame({'Actual': y1_test, 'Predicted': y1_pred})
df1

Actual      Predicted
28  103282.38  103901.896970
11  144259.40  132763.059931
10  146121.95  133567.903700
41   77798.83   72911.789767
2   191050.39  179627.925672
27  105008.31  115166.648648
38   81229.06   67113.576906
31   97483.56   98154.806868
22  110352.25  114756.115552
4   166187.94  169064.014088

In [30]:
print("For Original data")

print(reg.intercept_)
print(reg.coef_)

For Original data
42989.00816508666
[0.77884104 0.0293919  0.03471025]


In [31]:
print("\nFor X/2 data")
print(regressor1.intercept_)
print(regressor1.coef_)


For X/2 data
42989.00816508669
[0.77884104 0.0587838  0.03471025]
