In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Dataset:
It is having investment and profit of 50 Starts up at USA.

In [22]:
Score = pd.read_csv("startup.csv")
Score.shape
Score.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [23]:
#preparing the data
X = Score.drop('Profit', axis=1)
y = Score['Profit']

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [25]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [26]:
#printing parameters:
print(reg.intercept_)
print(reg.coef_)

42989.00816508666
[0.77884104 0.0293919  0.03471025]


In [27]:
#making predictions:
y_pred = reg.predict(X_test)

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


% Administration column is divided by 2

In [29]:
Score = pd.read_csv("startup.csv")
Score.shape
Score.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [30]:
Score['Marketing Spend'] = (Score['Marketing Spend'] + 100000)

In [31]:
Score.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        571784.10  192261.83
1  162597.70       151377.59        543898.53  191792.06
2  153441.51       101145.55        507934.54  191050.39
3  144372.41       118671.85        483199.62  182901.99
4  142107.34        91391.77        466168.42  166187.94

In [32]:
#preparing the data
X1 =Score.drop('Profit', axis=1)
y1= Score['Profit']

In [33]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=0)

In [34]:
regressor1 = LinearRegression()
regressor1.fit(X1_train, y1_train)

LinearRegression()

In [35]:
y1_pred = regressor1.predict(X1_test)

In [36]:
df1 = pd.DataFrame({'Actual': y1_test, 'Predicted': y1_pred})
df1

Actual      Predicted
28  103282.38  103901.896970
11  144259.40  132763.059931
10  146121.95  133567.903700
41   77798.83   72911.789767
2   191050.39  179627.925672
27  105008.31  115166.648648
38   81229.06   67113.576906
31   97483.56   98154.806868
22  110352.25  114756.115552
4   166187.94  169064.014088

In [37]:
print("For Original data")

print(reg.intercept_)
print(reg.coef_)

For Original data
42989.00816508666
[0.77884104 0.0293919  0.03471025]


In [38]:
print("\nFor (X+100000)  data")
print(regressor1.intercept_)
print(regressor1.coef_)


For (X+100000)  data
39517.98267814462
[0.77884104 0.0293919  0.03471025]


In [39]:
42989.00816508666 - .03471025*100000 

39517.98316508666

In [40]:
40049.81825533144

40049.81825533144